djangoProject/dj/bbs/urls.py
from django.urls import path
from . import views

app_name='bbs'
#127.0.0.1:8000/bbs/

urlpatterns = [
    path('list/',views.b_list,name='b_list'),
    path('create/',views.b_create,name='b_create'),
    # form, DB저장,  GET/POST

    path('<int:board_id>/detail/',views.b_detail,name='b_detail'),

    path('<int:board_id>/update/',views.b_update,name='b_update'),
    path('<int:board_id>/upddateProcess/',views.b_update_process,name='b_update_process'),

    path('<int:board_id>/like/',views.b_like,name='b_like'),
    path('<int:board_id>/delete/',views.b_delete,name='b_delete'),

    path('commentCreate/', views.c_create, name='c_create'),
]

djangoProject/dj/lecture/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',TemplateView.as_view(template_name='index.html'),name='home'),
    # http://127.0.0.1
    path('users/',include('users.urls')),
    # http://127.0.0.1/users/~~
    path('bbs/',include('bbs.urls')),
    # http://127.0.0.1/bbs/~~~

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
   #js, css, image  정적 파일 관리 (Django가 webserver 역활을 함)

djangoProject/dj/bbs/models.py
from django.db import models

# Create your models here.
class Board(models.Model):

    #b_no = models.IntegerField(primary_key=True)
    b_title = models.CharField(max_length=100)
    b_author = models.CharField(max_length=20)
    b_content = models.CharField(max_length=500)
    b_date = models.DateTimeField(auto_now_add=True)
    b_comment_count = models.IntegerField(default=0)
    b_like_count = models.IntegerField(default=0)

    def __str__(self):
        return self.b_title

class Comment(models.Model):
    c_author = models.CharField(max_length=20)
    c_content = models.CharField(max_length=500)
    board = models.ForeignKey(Board,on_delete=models.CASCADE)

    def __str__(self):
        return self.c_content

djangoProject/dj/bbs/forms.py
from django import forms
from .models import Board

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['b_title','b_author','b_content']

        labels = {
            'b_title' : '글제목',
            'b_author' : '글 작성자',
            'b_content' : '글 내용'
        }
        widgets= {
            'b_title' : forms.TextInput(
                attrs={
                    'class':'form-control w-50',
                    'placeholder':'글 제목을 입력하세요',
                }
            ),
            'b_author' : forms.TextInput(
                attrs={
                    'class':'form-control w-25',
                    'placeholder':'글 작성자를 입력하세요',
                }
            ),
            'b_content' : forms.Textarea(
                attrs={
                    'class':'form-control w-75',
                    'placeholder':'글 내용을 입력하세요',
                }
            )
        }

class BoardDetailForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = '__all__'

        labels = {
            'b_title' : '글제목',
            'b_author' : '글 작성자',
            'b_content' : '글 내용',
            'b_comment_count' : '댓글 개수',
            'b_like_count' : '좋아요 개수'
        }

        widgets= {
            'b_title' : forms.TextInput(
                attrs={
                    'class':'form-control w-50',
                }
            ),
            'b_author' : forms.TextInput(
                attrs={
                    'class':'form-control w-25',
                }
            ),
            'b_content' : forms.Textarea(
                attrs={
                    'class':'form-control w-75',
                }
            ),
            'b_comment_count': forms.TextInput(
                attrs={
                    'class': 'form-control w-25',
                }
            ),
            'b_like_count' : forms.TimeInput(
                attrs={
                    'class' : 'form-control w-25',
                }
            )
        }


    def show_board_detail(self):
        fields= list(BoardDetailForm().base_fields)
        for field in fields:
            self.fields[field].widget.attrs.update({
                'readonly' : 'readonly'
            })

    def show_board_update(self):
        self.fields['b_like_count'].widget.attrs.update({
            'readonly':'readonly'
        })
        self.fields['b_comment_count'].widget.attrs.update({
            'readonly':'readonly'
        })

djangoProject/dj/bbs/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Board
from .forms import BoardForm,BoardDetailForm

# Create your views here.
def b_list(request):

    # 로그인된 인증된 사람 인지 확인 합니다.
    if request.user.is_authenticated:
        posts = Board.objects.all().order_by('-id')
        return render(request,'bbs/list.html',{'posts':posts})
    else:
        return redirect('home')

def b_create(request):
    if request.method == 'GET':
        board_form = BoardForm()
    else:
        board_form = BoardForm(request.POST)
        if board_form.is_valid():
            board_form.save()
            return redirect("bbs:b_list")

    return render(request,'bbs/create.html',{
        'board_form':board_form
    })

def b_detail(request,board_id):
    post = get_object_or_404(Board,id=board_id)

    board_detail_form = BoardDetailForm(instance=post)
    board_detail_form.show_board_detail()
    # 입력양식이 모두 readonly로 변경

    return render(request,'bbs/detail.html',{
        'board_detail_form':board_detail_form
    })

def b_update(request,board_id):
    post = get_object_or_404(Board,id=board_id)     #post하나 가져오고
    board_detail_form = BoardDetailForm(instance=post)  #가져온 post로 값이 있는 폼만들기
    
    board_detail_form.show_board_update()  # 글제목, 작성자, 내용만 수정처리 됨

    return render(request,'bbs/update.html',{
        'board_detail_form':board_detail_form
    })


def b_update_process(request,board_id):
    # 수정처리 전(DB가 반영되기 전) POST
    post = get_object_or_404(Board,id=board_id)

    if request.method == "POST":
        #수정된 내용을 가지고 있는 ModelForm객체를 생성한거에요
        board_detail_form = BoardDetailForm(request.POST, instance=post)

        if board_detail_form.is_valid():
            board_detail_form.save()

            board_detail_form.show_board_detail() # 모두 readonly 변경

            return render(request,'bbs/detail.html',{'board_detail_form':board_detail_form})

    return redirect('home')

def b_delete(request,board_id):
    # 삭제할 post 1개 받아오고,  삭제하고,  리턴
    post = get_object_or_404(Board,id=board_id)
    post.delete()
    return redirect('bbs:b_list')

def b_like(request,board_id):
    post = get_object_or_404(Board,id=board_id)
    post.b_like_count += 1
    post.save()
    
    # 트랜젝션 처리를 하고 싶다면, 모델이 아닌 모델폼 객체를 사용해야 함
    # board_detail_form = BoardDetailForm(instance=post)
    # board_detail_form.b_like_count +=1
    # new_post =board_detail_form.save(commit=False)
    # board_detail_form.b_like_count =100
    # new_post.save()  #commit 처리 됨

    board_detail_form = BoardDetailForm(instance=post)
    board_detail_form.show_board_detail()  #readonly

    return render(request,'bbs/detail.html', {
        'board_detail_form':board_detail_form
        })


def c_create(request,board_id):
    pass

djangoProject/dj/templates/bbs/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block html_body %}
   
    <div class='container'>
        <h1>새글 작성</h1>

        <form method="post">
            {% csrf_token %}
            {% bootstrap_form board_form %}
            
            <br>

            <button class="btn btn-primary" 
                    type="submit">등록</button>
            <button class="btn btn-secondary"
                    type="button"
                    id="board_list_btn" onclick="location.href='{% url 'bbs:b_list' %}'">리스트로 돌아가기</button>
        <form>    
    </div>

{% endblock %}

djangoProject/dj/templates/bbs/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block html_body %}
    <div class='container'>
        <h1>글 상세 보기</h1>

        {% bootstrap_form board_detail_form %}

        <br>
        <button class='btn btn-secondary' 
            onclick="location.href='{% url 'bbs:b_list'%}'" >리스트로 돌아아기</button>
        <button class='btn btn-info' 
            onclick="location.href='{% url 'bbs:b_update' board_detail_form.initial.id %}'">수정</button>
        <button class='btn btn-danger' 
            onclick="location.href='{% url 'bbs:b_delete' board_detail_form.initial.id %}'">삭제</button>
        <button class='btn btn-warning'
            onclick="location.href='{% url 'bbs:b_like' board_detail_form.initial.id %}'">좋아요</button>
    </div>
    
{% endblock %}

djangoProject/dj/templates/bbs/list.html
{% extends "base.html" %}

{% block html_body %}
    <div class='container'>
        <h1>Bulletin Board System(BBS)</h1>
        <button class='btn btn-primary'
            onclick="location.href='{% url 'bbs:b_create' %}'">새글작성</button>

        <table class='table table-hover'>
            <thead>
                <tr>
                    <th>#</th>
                    <th>글제목</th>
                    <th>작성자</th>
                    <th>작성일</th>
                    <th>댓글수</th>
                    <th>좋아요 수</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                    <tr>
                        <td>{{post.id}}</td>
                        {% comment %} <td><a href="/bbs/{{post.id}}/detail/">{{post.b_title}}</a></td> {% endcomment %}
                        <td><a href="{% url 'bbs:b_detail' post.id %}">{{post.b_title}}</a></td>
                        <td>{{post.b_author}}</td>
                        <td>{{post.b_date}}</td>
                        <td>{{post.b_comment_count}}</td>
                        <td>{{post.b_like_count}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock html_body %}

djangoProject/dj/templates/bbs/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block html_body %}
    <div class='container'>
        <h1>글 수정하기</h1>

        <form action="{% url 'bbs:b_update_process' board_detail_form.initial.id %}" method='post' >
            {% csrf_token %}
            {% bootstrap_form board_detail_form %}

            <br>
            <button class='btn btn-secondary' 
                onclick="location.href='{% url 'bbs:b_list'%}'" >리스트로 돌아아기</button>
            <button class='btn btn-info' 
                type='submit' >수정적용</button>
        </form>            
    </div>
    
{% endblock %}